// SPDX-License-Identifier: BUSL-1.1
pragma solidity 0.8.34;

library Errors {
    error AccountingMandatory();
    error AlreadyGuardian();
    error AlreadyOperator();
    error AmountOutTooLow();
    error BridgeEncoderDoesNotExist();
    error CctpDomainNotRegistered();
    error DirectManageFlashLoanCall();
    error ExceededMaxFee(uint256 fee, uint256 max);
    error InstructionsMismatch();
    error InvalidAccounting();
    error InvalidBpsValue();
    error InvalidDataHash();
    error InvalidDebtFlag();
    error InvalidDecimals();
    error InvalidFeedRoute();
    error InvalidFeeRate();
    error InvalidFlashLoanProvider();
    error InvalidFlashLoanTaker();
    error InvalidInputToken();
    error InvalidInstructionProof();
    error InvalidInstructionType();
    error InvalidLzSentAmount();
    error InvalidPositionChangeDirection();
    error LzEndpointIdNotRegistered();
    error ManageFlashLoanReentrantCall();
    error MaxValueLossExceeded();
    error MinOutputAmountExceedsInputAmount();
    error MismatchedLengths();
    error NegativeTokenPrice(address priceFeed);
    error NotFlashLoanModule();
    error NotGuardian();
    error NotMorpho();
    error NotOperator();
    error OftAlreadyRegistered();
    error OftMismatch();
    error OftNotRegistered();
    error Paused();
    error ProtectedCctpDomain();
    error ProtectedChainId();
    error ProtectedGuardian();
    error PriceFeedRouteNotRegistered(address token);
    error PriceFeedStale(address priceFeed, uint256 updatedAt);
    error RecipientAlreadyWhitelisted();
    error RecipientNotWhitelisted();
    error RouteAlreadyRegistered();
    error RouteNotRegistered();
    error Suspended();
    error SwapFailed();
    error SwapperTargetsNotSet();
    error SweepNativeFailed();
    error TransferFromSafeFailed();
    error UnauthorizedCaller();
    error ZeroAddress();
    error ZeroChainId();
    error ZeroLzEndpointId();
    error ZeroPositionId();
    error ZeroRefundAddress();
    error ZeroSalt();
}
